### ISSUE TITLE
Renaming project doesn't change slug

### ISSUE THREAD

**Issue by knutole** [mapic/mapic.js#21]
When renaming project, the slug should also be updated. 

- [ ] Ensure slug is updated
- [ ] Ensure slug is available before allowing project rename
- [ ] Add test

**Comment by destromas1** [comment]
@knutole `Ensure slug is updated` is done . Will check about `Ensure slug is available before allowing project rename`

**Comment by knutole** [comment]
Ok, great. Ensuring slug is available requires a server call. There should be an API endpoint and `api.user.js` function for this already.

**Comment by destromas1** [comment]
@knutole I will also work on the Server side API https://github.com/mapic/engine/blob/master/api/api.project.js#L899

**Comment by knutole** [comment]
OK, great
