### ISSUE TITLE
Renaming project doesn't update in GUI, needs refresh

### ISSUE THREAD

**Issue by knutole** [mapic/mapic.js#27]
- [ ] Ensure new project name is reflected in GUI instantly
- [ ] Ensure url in browser is updated with new, unique & valid project `slug`

**Comment by destromas1** [comment]
@knutole 

In this PR https://github.com/mapic/mapic.js/pull/18 , this issue will be resolved.
Cooking!

**Comment by knutole** [comment]
great job @destromas1 👍
