### ISSUE TITLE
Test Framework + Environment integration

### ISSUE THREAD

**Issue by destromas1** [mapic/mapic.js#6]
## List of implemented tests
- [x] Created `app` object
- [x] Correct version
- [ ] Clicking "new project" button, filling in form (in all variations), and creating project.
- [ ] Clicking edit button and renaming project.
- [ ] Adding/removing users to project by clicking.
- [ ] Deleting project by clicking on Edit/Delete button.
- [ ] Changing style of layer (in all variations)
- [ ] Adding layer to layermenu by clicking

**Comment by destromas1** [comment]
We can go for 2 Ways ->
1. Unit Testing with HTTP Mocking
2. End to end Integration testing

But as Mapic has server side Testing , we can go for only frontend based Unit Testing with Mocking

We can use Karma , (Jasmine/Mocha - will decide today) , Sinon

**Comment by knutole** [comment]
Some thoughts:

1. We should focus on functional/integration tests, _not_ unit tests, as there are not that many special unit-operations in our code.
2. Tests must be run in a browser environment, and we need to use either PhantomJS or Selenium or similar tool for this.
3. If possible, it would be nice to use Mocha/Chai, as these are libs we're already using for server-side testing.
4. Tests should cover all normal operations that the user would do manually, for example: 
    - [ ] Clicking "new project" button, filling in form (in all variations), and creating project.
    - [ ] Clicking edit button and renaming project.
    - [ ] Adding/removing users to project by clicking.
    - [ ] Deleting project by clicking on Edit/Delete button.
    - [ ] Changing style of layer (in all variations)
    - [ ] Adding layer to layermenu by clicking
    - [ ] etc...

**Comment by knutole** [comment]
## List of implemented tests
- [ ] Clicking "new project" button, filling in form (in all variations), and creating project.
- [ ] Clicking edit button and renaming project.
- [ ] Adding/removing users to project by clicking.
- [ ] Deleting project by clicking on Edit/Delete button.
- [ ] Changing style of layer (in all variations)
- [ ] Adding layer to layermenu by clicking

**Comment by knutole** [comment]
@destromas1  We have a problem with Raven. The `console.log`s all point to `raven.js`, which makes it very difficult to debug the code. 

Possible solutions:  
1. Only have Raven active in `prod` environment.
2. Try to have Raven work without hijacking the `console.log`, although this probably is not possible.
3. Google for solutions, I'm sure this has been annoying to others also.

<img width="730" alt="screen shot 2016-11-16 at 18 32 47" src="https://cloud.githubusercontent.com/assets/2197944/20358197/25a23700-ac2b-11e6-911b-9ad13a768af5.png">

**Comment by knutole** [comment]
Actually, nevermind, the code address is available in the stacktrace.. Sorry, my bad! @destromas1 
<img width="747" alt="screen shot 2016-11-16 at 21 29 16" src="https://cloud.githubusercontent.com/assets/2197944/20364532/cba07974-ac43-11e6-9bee-3fb70eb4d1b7.png">

**Comment by knutole** [comment]
Sentry works great though, got an email on that error! 👍

**Comment by destromas1** [comment]
@knutole Yup in the email , the details are available 👍

**Comment by knutole** [comment]
@destromas1 When adding commits, it's good if you can include link to this issue in the commit message, so we can more easily keep track of the commits related to this issue.

Like 
```bash
git commit -m "Added tests for blabla
     - see https://github.com/mapic/mapic.js/issues/6"
```
